line-length = 100
target-version = "py312"

[lint]
future-annotations = true
preview = true
select = [
    "F",
    "E",
    "W",
    "C90",
    "I",
    "N",
    "UP",
    "ANN",
    "ASYNC",
    "S",
    "B",
    "A",
    "C4",
    "DTZ",
    "EM",
    "FA",
    "ISC",
    "LOG",
    "G",
    "PIE",
    "T20",
    "PT",
    "RSE",
    "RET",
    "SLOT",
    "SIM",
    "TC",
    "ARG",
    "PTH",
    "PL",
    "TRY",
    "FAST",
    "PERF",
    "FURB",
    "RUF",
]
ignore = [
    "assert",
    "magic-value-comparison",
    "ambiguous-unicode-character-comment",
    "no-self-use",
    "any-type",
    "call-datetime-strptime-without-zone",
    "line-too-long",
    "suspicious-non-cryptographic-random-usage",
    "missing-type-kwargs",
    "too-many-statements-in-try-clause",
]

[lint.per-file-ignores]
"**/__init__.py" = ["undefined-local-with-import-star", "unused-import"]
"test.py" = ["ALL"]

[lint.flake8-type-checking]
runtime-evaluated-base-classes = [
    "pydantic.BaseModel",
    "pydantic_settings.BaseSettings",
]

[lint.mccabe]
max-complexity = 15

[lint.pydocstyle]
convention = "google"

[lint.isort]
split-on-trailing-comma = false

[format]
skip-magic-trailing-comma = true
